### PR TITLE
Add (<&&>),(<||>)

### PR DESCRIPTION
**Pull request by talw**
There was a great suggestion in issue #109. 
But it seems like it wasn't realized as the issue is 5 months old.
So I took it upon myself :)

### CODE REVIEW

**Comment by snoyberg** [comment]
LGTM. @gregwebs do you have any comment on fixities here? I'm particularly bad at making decisions on those.

**Comment by gregwebs** [comment]
I don't know visitors because I don't crea

**Comment by gregwebs** [comment]
I don't know visitors because I don't create operators. Seems like they should be similar to the non-applicative.

**Comment by snoyberg** [comment]
Looks like that's what @talw chose here, which seems reasonable to me as well. I'll go ahead and merge it then :)

**Pull request merged**
